In [1]:
from sklearn import datasets
import matplotlib.pyplot as plt
from sklearn.neural_network import MLPClassifier

digits = datasets.load_digits()

x = digits.images.reshape((digits.images.shape[0], digits.images.shape[1]*digits.images.shape[2]))
y = digits.target

x_train = x[:1000]
y_train = y[:1000]

x_test = x[1000:]
y_test = y[1000:]

[[ 0.  0.  5. ...  0.  0.  0.]
 [ 0.  0.  0. ... 10.  0.  0.]
 [ 0.  0.  0. ... 16.  9.  0.]
 ...
 [ 0.  0.  3. ...  9.  0.  0.]
 [ 0.  0.  0. ...  6.  0.  0.]
 [ 0.  0.  9. ... 10.  0.  0.]]
[0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 9 5 5 6 5 0
 9 8 9 8 4 1 7 7 3 5 1 0 0 2 2 7 8 2 0 1 2 6 3 3 7 3 3 4 6 6 6 4 9 1 5 0 9
 5 2 8 2 0 0 1 7 6 3 2 1 7 4 6 3 1 3 9 1 7 6 8 4 3 1 4 0 5 3 6 9 6 1 7 5 4
 4 7 2 8 2 2 5 7 9 5 4 8 8 4 9 0 8 9 8 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7
 8 9 0 1 2 3 4 5 6 7 8 9 0 9 5 5 6 5 0 9 8 9 8 4 1 7 7 3 5 1 0 0 2 2 7 8 2
 0 1 2 6 3 3 7 3 3 4 6 6 6 4 9 1 5 0 9 5 2 8 2 0 0 1 7 6 3 2 1 7 3 1 3 9 1
 7 6 8 4 3 1 4 0 5 3 6 9 6 1 7 5 4 4 7 2 8 2 2 5 5 4 8 8 4 9 0 8 9 8 0 1 2
 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 9 5 5 6 5 0 9 8 9
 8 4 1 7 7 3 5 1 0 0 2 2 7 8 2 0 1 2 6 3 3 7 3 3 4 6 6 6 4 9 1 5 0 9 5 2 8
 2 0 0 1 7 6 3 2 1 7 4 6 3 1 3 9 1 7 6 8 4 3 1 4 0 5 3 6 9 6 1 7 5 4 4 7 2
 8 2 2 5 7 9 5 4 8 8 4 9 0 8 9 3 0 1 2 3 4 5 6 7 8 9 0 1 2

In [11]:
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier(hidden_layer_sizes=(15,), 
                    activation='logistic', 
                    solver='sgd', 
                    tol=1e-4, 
                    learning_rate_init=.1, 
                    verbose=False)

mlp.fit(x_train,y_train)
print(mlp.intercepts_[0])
print("---------------------------------------------")
print(mlp.coefs_[0])

[ 0.04275856 -0.10496446  0.06754105  0.06499466 -0.09878878  0.02474222
  0.08911749  0.1516455   0.07673075 -0.04371152 -0.17220179  0.11637978
  0.02712973  0.0129169   0.17782702]
---------------------------------------------
[[ 5.54392999e-02 -5.22545066e-02  9.45706852e-02  1.16634560e-01
   8.84598608e-03  1.30921650e-01  4.52421799e-02 -5.36933284e-02
   4.87330898e-02 -1.13138448e-01 -7.56882410e-02  4.42136052e-02
   5.22819346e-02 -5.36458156e-02 -3.23739744e-02]
 [ 7.52960273e-02  1.51655264e-01  3.36446667e-02  5.52829711e-02
  -1.05724045e-01 -1.82024515e-01 -1.10883148e-02  1.94478270e-03
  -1.96731318e-01  1.49228498e-01  5.79494045e-03 -1.84333303e-01
  -1.58744764e-01  5.84659901e-03 -1.00317451e-01]
 [ 1.16532805e-01  3.67954333e-01 -2.74899149e-01  1.35513124e-01
  -1.15686327e-01 -1.93478595e-01 -6.80265034e-02 -6.06579624e-02
  -1.15804013e-01  2.39194188e-01 -1.37669925e-01  3.06212095e-01
   7.15574381e-02 -3.08947857e-02 -3.21765976e-03]
 [-8.86870215e-02  3.91

In [3]:
predictions = mlp.predict(x_test)

In [4]:
from sklearn.metrics import confusion_matrix

confusion_matrix(y_test, predictions)

array([[75,  0,  0,  0,  1,  1,  2,  0,  0,  0],
       [ 0, 69,  0,  1,  1,  0,  0,  1,  0,  8],
       [ 0,  0, 72,  5,  0,  0,  0,  0,  0,  0],
       [ 0,  6,  0, 63,  0,  3,  0,  2,  4,  1],
       [ 0,  0,  0,  0, 79,  0,  0,  0,  0,  4],
       [ 0,  2,  0,  0,  0, 79,  1,  0,  0,  0],
       [ 0,  0,  0,  0,  0,  0, 79,  0,  1,  0],
       [ 0,  0,  0,  0,  0,  0,  0, 77,  0,  3],
       [ 0,  5,  0,  0,  1,  1,  0,  1, 66,  2],
       [ 0,  2,  0,  1,  0,  0,  0,  1,  2, 75]], dtype=int64)

In [5]:
import pandas as pd

pd.crosstab(y_test, predictions, rownames=['True'], colnames=['Predicted'], margins=True)

Predicted   0   1   2   3   4   5   6   7   8   9  All
True                                                  
0          75   0   0   0   1   1   2   0   0   0   79
1           0  69   0   1   1   0   0   1   0   8   80
2           0   0  72   5   0   0   0   0   0   0   77
3           0   6   0  63   0   3   0   2   4   1   79
4           0   0   0   0  79   0   0   0   0   4   83
5           0   2   0   0   0  79   1   0   0   0   82
6           0   0   0   0   0   0  79   0   1   0   80
7           0   0   0   0   0   0   0  77   0   3   80
8           0   5   0   0   1   1   0   1  66   2   76
9           0   2   0   1   0   0   0   1   2  75   81
All        75  84  72  70  82  84  82  82  73  93  797

In [20]:
import pandas as pd
import numpy as np

In [21]:
data = pd.read_csv("digits.csv", header = None)

In [22]:
data

0   1   2   3   4   5   6   7   8   9   ...  55  56  57  58  59  60  61  \
0      0   0   5  13   9   1   0   0   0   0  ...   0   0   0   6  13  10   0   
1      0   0   0  12  13   5   0   0   0   0  ...   0   0   0   0  11  16  10   
2      0   0   0   4  15  12   0   0   0   0  ...   0   0   0   0   3  11  16   
3      0   0   7  15  13   1   0   0   0   8  ...   0   0   0   7  13  13   9   
4      0   0   0   1  11   0   0   0   0   0  ...   0   0   0   0   2  16   4   
5      0   0  12  10   0   0   0   0   0   0  ...   0   0   0   9  16  16  10   
6      0   0   0  12  13   0   0   0   0   0  ...   0   0   0   1   9  15  11   
7      0   0   7   8  13  16  15   1   0   0  ...   0   0   0  13   5   0   0   
8      0   0   9  14   8   1   0   0   0   0  ...   0   0   0  11  16  15  11   
9      0   0  11  12   0   0   0   0   0   2  ...   0   0   0   9  12  13   3   
10     0   0   1   9  15  11   0   0   0   0  ...   0   0   0   1  10  13   3   
11     0   0   0   0  14  13   1   0   0   0  ...   0   0   0   0   1  13  16   
12     0   0   5  12   1   0   0   0   0   0  ...   2   0   0   3  11   8  13   
13     0   2   9  15  14   9   3   0   0   4  ...   0   0   2  12  12  13  11   
14     0   0   0   8  15   1   0   0   0   0  ...   0   0   0   0  10  15   4   
15     0   5  12  13  16  16   2   0   0  11  ...   0   0   4  15  16   2   0   
16     0   0   0   8  15   1   0   0   0   0  ...   2   0   0   0   7  15  16   
17     0   0   1   8  15  10   0   0   0   3  ...   0   0   0   0  11   9   0   
18     0   0  10   7  13   9   0   0   0   0  ...   0   0   0  11  14   5   0   
19     0   0   6  14   4   0   0   0   0   0  ...   2   0   0   7  16  16  13   
20     0   0   3  13  11   7   0   0   0   0  ...   0   0   0   2  12  13   4   
21     0   0   0   2  16  16   2   0   0   0  ...   0   0   0   0   2  12  15   
22     0   0   8  16   5   0   0   0   0   1  ...   0   0   0   7  12  12  12   
23     0   1   8  12  15  14   4   0   0   3  ...   0   0   0  14  15  11   2   
24     0   0   0   0  12   2   0   0   0   0  ...   0   0   0   0   0  12   8   
25     0   0  12   8   8   7   0   0   0   3  ...   0   0   0  11  14   9   0   
26     0   0   1  13  14   3   0   0   0   0  ...   0   0   0   3  12  15  14   
27     0   0   0   8  14  14   2   0   0   0  ...   0   0   0   0  12  13   1   
28     0   0  10  11   4   0   0   0   0   0  ...   0   0   0   8  14   7   1   
29     0   0   9  13   7   0   0   0   0   0  ...   2   0   0   7  12  12  12   
...   ..  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...  ..  ..  ..  ..  ..  ..  ..   
1767   0   0   0   2  16   1   0   0   0   0  ...   0   0   0   0   3  16   7   
1768   0   0   5  16  10   0   0   0   0   0  ...   0   0   0   4  15  16   8   
1769   0   0   9  12  14   6   0   0   0   0  ...   0   0   0  12  14   9   2   
1770   0   2  10  12  16   8   0   0   0   4  ...   0   0   2  14  16  12   9   
1771   0   0   0   6  12   6   0   0   0   0  ...   0   0   0   0   6  11  12   
1772   0   0   5  14  11   8   0   0   0   4  ...   0   0   0   7  15  12   5   
1773   0   0   2  13  10   0   0   0   0   0  ...   0   0   0   1  12  16  14   
1774   0   0   6  12  12   6   0   0   0   0  ...   0   0   0   2  11  10   4   
1775   0   0   6  16  16   3   0   0   0   0  ...   0   0   0  11  11   0   0   
1776   0   0  12  16  16   7   0   0   0   3  ...   0   0   0  10  12  12   4   
1777   0   0   0   2  14   0   0   0   0   0  ...   0   0   0   0   1  13   3   
1778   0   0   0   1  13   8   0   0   0   0  ...   0   0   0   0   0  15   7   
1779   0   0   3  10  16  16   4   0   0   0  ...   0   0   0   3  12   0   0   
1780   0   3  14  15   6   0   0   0   0   7  ...   0   0   4  15  13  12  11   
1781   0   0  10  16  14   5   0   0   0   2  ...   0   0   1  11  16  15   6   
1782   0   1  10  13   2   0   0   0   0  10  ...   0   0   0   9  13  11  10   
1783   0   0  15  13   1   0   0   0   0   0  ...   0   0   0  10  13  10   6   
1784   0   0   1  10  14  13   1   0 

In [23]:
x_train = np.array(data.iloc[0:1000,0:64])
y_train = np.array(data.iloc[0:1000,64:65]).reshape(1000)

x_test = np.array(data.iloc[1000:1797,0:64])
y_test = np.array(data.iloc[1000:1797,64:65]).reshape(797)