In [1]:
import numpy as np
np.random.seed(0)

x = np.arange(1,10)



In [2]:
import numpy as np
x = np.array([[0,1],
              [0,2],
              [1,3]])
y = np.array([1,1,1])
y = y.reshape(x.shape[0],1)
print(y)

[[1]
 [1]
 [1]]


In [4]:
w = np.random.random(x.shape[1])
print(w)
x = np.random.randint(10,size =(3,4,5))

[0.5488135  0.71518937]


In [5]:
print(x)
print(x[1,1:3,1:4])

[[[3 3 7 9 3]
  [5 2 4 7 6]
  [8 8 1 6 7]
  [7 8 1 5 9]]

 [[8 9 4 3 0]
  [3 5 0 2 3]
  [8 1 3 3 3]
  [7 0 1 9 9]]

 [[0 4 7 3 2]
  [7 2 0 0 4]
  [5 5 6 8 4]
  [1 4 9 8 1]]]
[[5 0 2]
 [1 3 3]]
